#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/../../cli/node" ]; then
  "$basedir/../../cli/node"  "$basedir/../../cli/bin/cli" "$@"
  ret=$?
else
  node  "$basedir/../../cli/bin/cli" "$@"
  ret=$?
fi
exit $ret
